name: taup
title: The TauP Toolkit
version: 3.0.1
summary: "The TauP Toolkit: Flexible Seismic Travel-Time and Raypath Utilities"
description: |
  The TauP Toolkit is a seismic travel time calculator. In addition to travel
  times, it can calculate derivative information such as ray paths through the
  earth, pierce and turning points. It handles many types of velocity models and
  can calculate times for virtually any seismic phase with a phase parser.
  It is written in Java so it should run on any Java enabled platform.
  More info and docs at https://www.seis.sc.edu/TauP
base: core24
confinement: strict
grade: devel
apps:
  taup:
    command: bin/taup
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-${SNAP_ARCH}"
      PATH: "$SNAP/bin:$PATH:$JAVA_HOME/jre/bin"
    plugs: [home]
parts:
  taup:
    plugin: dump
    source: https://zenodo.org/records/15426279/files/TauP-3.0.1.zip
    source-type: zip
    stage-packages:
      - openjdk-11-jdk-headless
    stage:
      - bin
      - lib
      - VERSION
      - README.md
      - docs
    override-build: |
      cp -r TauP-3.0.1/* $SNAPCRAFT_PART_INSTALL
