name: Java CI with Gradle

# execute on any push and pull request
on:
  push:
  pull_request:

# only execute one test simultaneously
# terminate running tests if a new push happens
concurrency:
  group: ${{ github.actor }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 11
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Build with Gradle
      run: ./gradlew installDist
    - name: Test with Gradle
      run: ./gradlew  check
